### ISSUE TITLE
Kuiper process crashed unexpectedly

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#144]
1) Error configuration in sink, which will lead to fail to start rule
2) Framework terminate the rule, and invokes ``close`` method directly. However, since the ``open`` method has not been invoked yet, then any code tries to close the connections will produce error.  Below is an example,

```
goroutine 66 [running]:
github.com/edgexfoundry/go-mod-messaging/internal/pkg/zeromq.(*zeromqClient).Disconnect(0xc0002bc000, 0x1, 0x1)
        /Users/rockyjin/go/pkg/mod/github.com/edgexfoundry/go-mod-messaging@v0.1.14/internal/pkg/zeromq/client.go:194 +0xb4
github.com/emqx/kuiper/xstream/extensions.(*EdgexSource).Close(0xc000220100, 0x49d5fe0, 0xc0000c2d20, 0x439ea95, 0xc00018a620)
        /Users/rockyjin/Downloads/workspace/edge/src/kuiper/xstream/extensions/edgex_source.go:224 +0x33
github.com/emqx/kuiper/xstream/nodes.(*SourceNode).close(0xc0001b40a0, 0x49d5fe0, 0xc0000c2d20, 0x49d6060, 0xc00018a620)
        /Users/rockyjin/Downloads/workspace/edge/src/kuiper/xstream/nodes/source_node.go:179 +0x7a
github.com/emqx/kuiper/xstream/nodes.(*SourceNode).Open.func1.1(0xc0001b40a0, 0xc0001ac0c0, 0x49d5fe0, 0xc0000c2d20, 0x49d6060, 0xc00018a620, 0xc000216150, 0xc00023e140, 0x0)
        /Users/rockyjin/Downloads/workspace/edge/src/kuiper/xstream/nodes/source_node.go:120 +0xa23
created by github.com/emqx/kuiper/xstream/nodes.(*SourceNode).Open.func1
        /Users/rockyjin/Downloads/workspace/edge/src/kuiper/xstream/nodes/source_node.go:80 +0x262

```

**Comment by jinfahua** [comment]
Handle it by extension code, need to detect the connection status before closing it.
